[build]
  base = "layout-generator"
  command = "npm run build"
  publish = "layout-generator/build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200